rm(list=ls())
install.packages("Hmisc")
data1<-read.csv("C:/trial/COVID19_line_list_datap.csv")
require("Hmisc")
describe(data1)
data1$death_dummy <- as.integer(data1$death != 0)
sum(data1$death_dummy) / nrow(data1)
dead = subset(data1, death_dummy == 1)
alive = subset(data1, death_dummy == 0)
mean(dead$age, na.rm = TRUE)
mean(alive$age, na.rm = TRUE)
t.test(alive$age, dead$age, alternative="two.sided", conf.level = 0.99)
men = subset(data1, gender == "male")
women = subset(data1, gender == "female")
mean(men$death_dummy, na.rm = TRUE)
mean(women$death_dummy, na.rm = TRUE)
t.test(men$death_dummy, women$death_dummy, alternative="two.sided", conf.level = 0.99)

